

const
  { highly abbreviated list of windows errors                                 }

  { ------------------------------------------------------------------------- }
  { Cannot create a file when that file already exists.                       }

  ERROR_ALREADY_EXISTS                                             =       183;


// END of file
// ----------------------------------------------------------------------------